name: Pull Request workflow

on:
  - pull_request

jobs:
  cloudformation-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout
      - name: Linter install
        uses: scottbrenner/cfn-lint-action
        with:
          command: cfn-lint -t ./templates/*.yaml
